<ApLocationMixed>:
    text: "Server:"
    size_hint_x: None
    canvas:
        Color:
            rgb: 0,0,0
        Rectangle:
            pos: self.x - app.loc_border-self.width/2, self.y - app.loc_border-self.height/2
            size: self.width + (app.loc_border * 2), self.height + (app.loc_border * 2)
        Color:
            rgb: self.color
        Rectangle:
            pos: self.x-self.width/2, self.y-self.height/2
            size: self.size

<ApLocationSplit>:
    text: "Server:"
    size_hint_x: None
    color_2: (1, 0, 0)
    color_4: (1, 1, 0)
    color_1: (0, 1, 0)
    color_3: (0, 0, 1)
    canvas:
        Color:
            rgb: 0,0,0
        Rectangle:
            pos: self.x - app.loc_border-self.width/2, self.y - app.loc_border-self.height/2
            size: self.width + (app.loc_border * 2), self.height + (app.loc_border * 2)
        Color:
            rgb: self.color_1
        Triangle:
            points: self.x, self.y, self.x - (self.width / 2), self.y + (self.height /2), self.x + (self.width / 2), self.y + (self.height /2)
        Color:
            rgb: self.color_3
        Triangle:
            points: self.x, self.y, self.x + (self.width / 2), self.y - (self.height /2), self.x + (self.width / 2), self.y + (self.height /2)
        Color:
            rgb: self.color_2
        Triangle:
            points: self.x, self.y, self.x - (self.width / 2), self.y - (self.height /2), self.x + (self.width / 2), self.y - (self.height /2)
        Color:
            rgb: self.color_4
        Triangle:
            points: self.x, self.y, self.x - (self.width / 2), self.y - (self.height /2), self.x - (self.width / 2), self.y + (self.height /2)

<MappingTracker>:
    BoxLayout:
        orientation: "vertical"
        BoxLayout:
            orientation: "horizontal"
            pos_hint: {'center_x': 0.5}
            size_hint: None, None
            size: self.minimum_size
            spacing: dp(10)
            MDButton:
                style: "filled"
                disabled: not app.mapping_preset_enabled
                on_release: app.load_mapping_preset_dialog()
                MDButtonText:
                    text: "Load Preset"
            MDDropDownItem:
                id: mapping_tab_list
                on_release: app.open_mapping_dropdown(self)
                MDDropDownItemText:
                    id: mapping_drop_text
                    text: "Mapping Tab: " + app.mapping_current_tab
        ApAsyncImage:
            id: tracker_map
            source: app.mapping_source
            fit_mode: "contain"
        Widget:
            id: location_canvas
            pos_hint: {'center_x': 0.5, 'center_y': 0.5}
            size_hint: '0.01dp', '0.02dp'
            canvas.before:
                PushMatrix:
                Rotate:
                    origin: tracker_map.center
                    angle: 180
                    axis: 1, 0, 0
                Translate:
                    xy: (tracker_map.x + (tracker_map.width - tracker_map.norm_image_size[0])/2, tracker_map.y + (tracker_map.height - tracker_map.norm_image_size[1])/2)
                Scale:
                    origin: 0,0
                    x: tracker_map.norm_image_size[0] / tracker_map.texture_size[0] if tracker_map.texture_size[0] > 0 else 1
                    y: tracker_map.norm_image_size[1] / tracker_map.texture_size[1] if tracker_map.texture_size[1] > 0 else 1
            canvas.after:
                PopMatrix:
